# Generated by Django 4.0.4 on 2022-10-12 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_balance', models.FloatField(default=0.0)),
                ('total_profit', models.FloatField(default=0.0)),
                ('total_bonus', models.FloatField(default=0.0)),
                ('total_referal_bonus', models.FloatField(default=0.0)),
                ('total_investment_plans', models.IntegerField(default=0)),
                ('total_active_investment_plans', models.IntegerField(default=0)),
                ('total_withdrawal', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
