# Generated by Django 4.0.4 on 2022-10-12 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto_for_payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto', models.CharField(max_length=200)),
                ('crypto_address', models.CharField(max_length=200)),
                ('network', models.CharField(default='none', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Deposite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=200)),
                ('ammount', models.FloatField()),
                ('profit_percent', models.FloatField()),
                ('time_count_for_trade', models.IntegerField(default=0)),
                ('time_of_trade', models.CharField(max_length=120)),
                ('transaction_mode', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved')], max_length=11)),
                ('trade_mode', models.CharField(choices=[('running', 'running'), ('pending', 'pending'), ('completed', 'completed')], max_length=11)),
                ('profit', models.FloatField(default=0.0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto', models.CharField(max_length=200)),
                ('crypto_address', models.CharField(max_length=200)),
                ('ammount_in_crypto', models.FloatField()),
                ('image_of_transact', models.ImageField(upload_to='verify_transact')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('deposite_transact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deposite.deposite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
